using UnityEngine;
using SkyHook;
using System.Linq;

namespace KeyViewer
{
    public static class AsyncInputCompat
    {
        public static bool AnyKey => AsyncInputManager.keyMask.Any();
        public static bool AnyKeyUp => AsyncInputManager.keyUpMask.Any();
        public static bool AnyKeyDown => AsyncInputManager.keyDownMask.Any();
        public static bool GetKey(KeyCode code) => AsyncInput.GetKey(Convert(code));
        public static bool GetKeyUp(KeyCode code) => AsyncInput.GetKeyUp(Convert(code));
        public static bool GetKeyDown(KeyCode code) => AsyncInput.GetKeyDown(Convert(code));
        public static KeyCode Convert(KeyLabel label)
        {
            switch (label)
            {
                case KeyLabel.Escape: return KeyCode.Escape;
                case KeyLabel.F1: return KeyCode.F1;
                case KeyLabel.F2: return KeyCode.F2;
                case KeyLabel.F3: return KeyCode.F3;
                case KeyLabel.F4: return KeyCode.F4;
                case KeyLabel.F5: return KeyCode.F5;
                case KeyLabel.F6: return KeyCode.F6;
                case KeyLabel.F7: return KeyCode.F7;
                case KeyLabel.F8: return KeyCode.F8;
                case KeyLabel.F9: return KeyCode.F9;
                case KeyLabel.F10: return KeyCode.F10;
                case KeyLabel.F11: return KeyCode.F11;
                case KeyLabel.F12: return KeyCode.F12;
                case KeyLabel.F13: return KeyCode.F13;
                case KeyLabel.F14: return KeyCode.F14;
                case KeyLabel.F15: return KeyCode.F15;
                case KeyLabel.Grave: return KeyCode.BackQuote;
                case KeyLabel.Alpha1: return KeyCode.Alpha1;
                case KeyLabel.Alpha2: return KeyCode.Alpha2;
                case KeyLabel.Alpha3: return KeyCode.Alpha3;
                case KeyLabel.Alpha4: return KeyCode.Alpha4;
                case KeyLabel.Alpha5:  return KeyCode.Alpha5;
                case KeyLabel.Alpha6: return KeyCode.Alpha6;
                case KeyLabel.Alpha7: return KeyCode.Alpha7;
                case KeyLabel.Alpha8: return KeyCode.Alpha8;
                case KeyLabel.Alpha9: return KeyCode.Alpha9;
                case KeyLabel.Alpha0: return KeyCode.Alpha0;
                case KeyLabel.Minus: return KeyCode.Minus;
                case KeyLabel.Equal: return KeyCode.Equals;
                case KeyLabel.Backspace: return KeyCode.Backspace;
                case KeyLabel.Tab: return KeyCode.Tab;
                case KeyLabel.Q: return KeyCode.Q;
                case KeyLabel.W: return KeyCode.W;
                case KeyLabel.E: return KeyCode.E;
                case KeyLabel.R: return KeyCode.R;
                case KeyLabel.T: return KeyCode.T;
                case KeyLabel.Y: return KeyCode.Y;
                case KeyLabel.U: return KeyCode.U;
                case KeyLabel.I: return KeyCode.I;
                case KeyLabel.O: return KeyCode.O;
                case KeyLabel.P: return KeyCode.P;
                case KeyLabel.LeftBrace: return KeyCode.LeftCurlyBracket;
                case KeyLabel.RightBrace: return KeyCode.RightCurlyBracket;
                case KeyLabel.BackSlash: return KeyCode.Backslash;
                case KeyLabel.CapsLock: return KeyCode.CapsLock;
                case KeyLabel.A: return KeyCode.A;
                case KeyLabel.S: return KeyCode.S;
                case KeyLabel.D: return KeyCode.D;
                case KeyLabel.F: return KeyCode.F;
                case KeyLabel.G: return KeyCode.G;
                case KeyLabel.H: return KeyCode.H;
                case KeyLabel.J: return KeyCode.J;
                case KeyLabel.K: return KeyCode.K;
                case KeyLabel.L: return KeyCode.L;
                case KeyLabel.Semicolon: return KeyCode.Semicolon;
                case KeyLabel.Apostrophe: return KeyCode.Quote;
                case KeyLabel.Enter: return KeyCode.Return;
                case KeyLabel.LShift: return KeyCode.LeftShift;
                case KeyLabel.Z: return KeyCode.Z;
                case KeyLabel.X: return KeyCode.X;
                case KeyLabel.C: return KeyCode.C;
                case KeyLabel.V: return KeyCode.V;
                case KeyLabel.B: return KeyCode.B;
                case KeyLabel.N: return KeyCode.N;
                case KeyLabel.M: return KeyCode.M;
                case KeyLabel.Comma: return KeyCode.Comma;
                case KeyLabel.Dot: return KeyCode.Period;
                case KeyLabel.Slash: return KeyCode.Slash;
                case KeyLabel.RShift: return KeyCode.RightShift;
                case KeyLabel.LControl: return KeyCode.LeftControl;
                case KeyLabel.Super: return KeyCode.LeftMeta;
                case KeyLabel.LAlt: return KeyCode.LeftAlt;
                case KeyLabel.Space: return KeyCode.Space;
                case KeyLabel.RAlt: return KeyCode.RightAlt;
                case KeyLabel.RControl: return KeyCode.RightControl;
                case KeyLabel.PrintScreen: return KeyCode.Print;
                case KeyLabel.ScrollLock: return KeyCode.ScrollLock;
                case KeyLabel.PauseBreak: return KeyCode.Pause;
                case KeyLabel.Insert: return KeyCode.Insert;
                case KeyLabel.Home: return KeyCode.Home;
                case KeyLabel.PageUp: return KeyCode.PageUp;
                case KeyLabel.Delete: return KeyCode.Delete;
                case KeyLabel.End: return KeyCode.End;
                case KeyLabel.PageDown: return KeyCode.PageDown;
                case KeyLabel.ArrowUp: return KeyCode.UpArrow;
                case KeyLabel.ArrowLeft: return KeyCode.LeftArrow;
                case KeyLabel.ArrowDown: return KeyCode.DownArrow;
                case KeyLabel.ArrowRight: return KeyCode.RightArrow;
                case KeyLabel.NumLock: return KeyCode.Numlock;
                case KeyLabel.KeypadSlash: return KeyCode.KeypadDivide;
                case KeyLabel.KeypadAsterisk: return KeyCode.KeypadMultiply;
                case KeyLabel.KeypadMinus: return KeyCode.KeypadMinus;
                case KeyLabel.Keypad1: return KeyCode.Keypad1;
                case KeyLabel.Keypad2: return KeyCode.Keypad2;
                case KeyLabel.Keypad3: return KeyCode.Keypad3;
                case KeyLabel.Keypad4: return KeyCode.Keypad4;
                case KeyLabel.Keypad5: return KeyCode.Keypad5;
                case KeyLabel.Keypad6: return KeyCode.Keypad6;
                case KeyLabel.Keypad7: return KeyCode.Keypad7;
                case KeyLabel.Keypad8: return KeyCode.Keypad8;
                case KeyLabel.Keypad9: return KeyCode.Keypad9;
                case KeyLabel.Keypad0: return KeyCode.Keypad0;
                case KeyLabel.KeypadDot: return KeyCode.KeypadPeriod;
                case KeyLabel.KeypadPlus: return KeyCode.KeypadPlus;
                case KeyLabel.KeypadEnter: return KeyCode.KeypadEnter;
                case KeyLabel.MouseLeft: return KeyCode.Mouse0;
                case KeyLabel.MouseRight: return KeyCode.Mouse1;
                case KeyLabel.MouseMiddle: return KeyCode.Mouse2;
                case KeyLabel.MouseX1: return KeyCode.Mouse3;
                case KeyLabel.MouseX2: return KeyCode.Mouse4;
                default: return KeyCode.None;
            }
        }
        public static KeyLabel Convert(KeyCode code)
        {
            switch (code)
            {
                case KeyCode.Escape: return KeyLabel.Escape;
                case KeyCode.F1: return KeyLabel.F1;
                case KeyCode.F2: return KeyLabel.F2;
                case KeyCode.F3: return KeyLabel.F3;
                case KeyCode.F4: return KeyLabel.F4;
                case KeyCode.F5: return KeyLabel.F5;
                case KeyCode.F6: return KeyLabel.F6;
                case KeyCode.F7: return KeyLabel.F7;
                case KeyCode.F8: return KeyLabel.F8;
                case KeyCode.F9: return KeyLabel.F9;
                case KeyCode.F10: return KeyLabel.F10;
                case KeyCode.F11: return KeyLabel.F11;
                case KeyCode.F12: return KeyLabel.F12;
                case KeyCode.F13: return KeyLabel.F13;
                case KeyCode.F14: return KeyLabel.F14;
                case KeyCode.F15: return KeyLabel.F15;
                case KeyCode.BackQuote: return KeyLabel.Grave;
                case KeyCode.Alpha1: return KeyLabel.Alpha1;
                case KeyCode.Alpha2: return KeyLabel.Alpha2;
                case KeyCode.Alpha3: return KeyLabel.Alpha3;
                case KeyCode.Alpha4: return KeyLabel.Alpha4;
                case KeyCode.Alpha5: return KeyLabel.Alpha5;
                case KeyCode.Alpha6: return KeyLabel.Alpha6;
                case KeyCode.Alpha7: return KeyLabel.Alpha7;
                case KeyCode.Alpha8: return KeyLabel.Alpha8;
                case KeyCode.Alpha9: return KeyLabel.Alpha9;
                case KeyCode.Alpha0: return KeyLabel.Alpha0;
                case KeyCode.Minus: return KeyLabel.Minus;
                case KeyCode.Equals: return KeyLabel.Equal;
                case KeyCode.Backspace: return KeyLabel.Backspace;
                case KeyCode.Tab: return KeyLabel.Tab;
                case KeyCode.Q: return KeyLabel.Q;
                case KeyCode.W: return KeyLabel.W;
                case KeyCode.E: return KeyLabel.E;
                case KeyCode.R: return KeyLabel.R;
                case KeyCode.T: return KeyLabel.T;
                case KeyCode.Y: return KeyLabel.Y;
                case KeyCode.U: return KeyLabel.U;
                case KeyCode.I: return KeyLabel.I;
                case KeyCode.O: return KeyLabel.O;
                case KeyCode.P: return KeyLabel.P;
                case KeyCode.LeftCurlyBracket: return KeyLabel.LeftBrace;
                case KeyCode.RightCurlyBracket: return KeyLabel.RightBrace;
                case KeyCode.Backslash: return KeyLabel.BackSlash;
                case KeyCode.CapsLock: return KeyLabel.CapsLock;
                case KeyCode.A: return KeyLabel.A;
                case KeyCode.S: return KeyLabel.S;
                case KeyCode.D: return KeyLabel.D;
                case KeyCode.F: return KeyLabel.F;
                case KeyCode.G: return KeyLabel.G;
                case KeyCode.H: return KeyLabel.H;
                case KeyCode.J: return KeyLabel.J;
                case KeyCode.K: return KeyLabel.K;
                case KeyCode.L: return KeyLabel.L;
                case KeyCode.Semicolon: return KeyLabel.Semicolon;
                case KeyCode.Quote: return KeyLabel.Apostrophe;
                case KeyCode.Return: return KeyLabel.Enter;
                case KeyCode.LeftShift: return KeyLabel.LShift;
                case KeyCode.Z: return KeyLabel.Z;
                case KeyCode.X: return KeyLabel.X;
                case KeyCode.C: return KeyLabel.C;
                case KeyCode.V: return KeyLabel.V;
                case KeyCode.B: return KeyLabel.B;
                case KeyCode.N: return KeyLabel.N;
                case KeyCode.M: return KeyLabel.M;
                case KeyCode.Comma: return KeyLabel.Comma;
                case KeyCode.Period: return KeyLabel.Dot;
                case KeyCode.Slash: return KeyLabel.Slash;
                case KeyCode.RightShift: return KeyLabel.RShift;
                case KeyCode.LeftControl: return KeyLabel.LControl;
                case KeyCode.LeftMeta: return KeyLabel.Super;
                case KeyCode.LeftAlt: return KeyLabel.LAlt;
                case KeyCode.Space: return KeyLabel.Space;
                case KeyCode.RightAlt: return KeyLabel.RAlt;
                case KeyCode.RightControl: return KeyLabel.RControl;
                case KeyCode.Print: return KeyLabel.PrintScreen;
                case KeyCode.ScrollLock: return KeyLabel.ScrollLock;
                case KeyCode.Pause: return KeyLabel.PauseBreak;
                case KeyCode.Insert: return KeyLabel.Insert;
                case KeyCode.Home: return KeyLabel.Home;
                case KeyCode.PageUp: return KeyLabel.PageUp;
                case KeyCode.Delete: return KeyLabel.Delete;
                case KeyCode.End: return KeyLabel.End;
                case KeyCode.PageDown: return KeyLabel.PageDown;
                case KeyCode.UpArrow: return KeyLabel.ArrowUp;
                case KeyCode.LeftArrow: return KeyLabel.ArrowLeft;
                case KeyCode.DownArrow: return KeyLabel.ArrowDown;
                case KeyCode.RightArrow: return KeyLabel.ArrowRight;
                case KeyCode.Numlock: return KeyLabel.NumLock;
                case KeyCode.KeypadDivide: return KeyLabel.KeypadSlash;
                case KeyCode.KeypadMultiply: return KeyLabel.KeypadAsterisk;
                case KeyCode.KeypadMinus: return KeyLabel.KeypadMinus;
                case KeyCode.Keypad1: return KeyLabel.Keypad1;
                case KeyCode.Keypad2: return KeyLabel.Keypad2;
                case KeyCode.Keypad3: return KeyLabel.Keypad3;
                case KeyCode.Keypad4: return KeyLabel.Keypad4;
                case KeyCode.Keypad5: return KeyLabel.Keypad5;
                case KeyCode.Keypad6: return KeyLabel.Keypad6;
                case KeyCode.Keypad7: return KeyLabel.Keypad7;
                case KeyCode.Keypad8: return KeyLabel.Keypad8;
                case KeyCode.Keypad9: return KeyLabel.Keypad9;
                case KeyCode.Keypad0: return KeyLabel.Keypad0;
                case KeyCode.KeypadPeriod: return KeyLabel.KeypadDot;
                case KeyCode.KeypadPlus: return KeyLabel.KeypadPlus;
                case KeyCode.KeypadEnter: return KeyLabel.KeypadEnter;
                case KeyCode.Mouse0: return KeyLabel.MouseLeft;
                case KeyCode.Mouse1: return KeyLabel.MouseRight;
                case KeyCode.Mouse2: return KeyLabel.MouseMiddle;
                case KeyCode.Mouse3: return KeyLabel.MouseX1;
                case KeyCode.Mouse4: return KeyLabel.MouseX2;
                default: return KeyLabel.Unknown;
            }
        }
    }
}
